<?php
$games = [
    'wolf3d' => [
        'name'    => 'Wolf3d',
        'tag'     => 'classic FPS',
        'license' => 'UNKNOWN',
        'git'     => 'https://github.com/jseidelin/wolf3d.git',
        'mobile'  => false,
        'desktop' => true,
    ],
    'loderunner_totalrecall' => [
        'name'    => 'Lode Runner',
        'tag'     => 'run, dig, old style',
        'license' => 'UNKNOWN',
        'git'     => 'https://github.com/SimonHung/LodeRunner_TotalRecall.git',
        'index'   => 'lodeRunner.html',
        'mobile'  => false,
        'desktop' => true,
    ],
    'klotski' => [
        'name'    => 'Klotski',
        'tag'     => 'free the block',
        'license' => 'UNKNOWN',
        'git'     => 'https://github.com/SimonHung/Klotski.git',
        'index'   => 'klotski.puzzle.html',
        'mobile'  => true,
        'desktop' => true,
    ],
    'taptaptap' => [
        'name'    => 'Tap Tap Tap',
        'tag'     => 'tap the blue',
        'license' => 'MIT',
        'git'     => 'https://github.com/MahdiF/taptaptap.git',
        'index'   => 'play/',
        'mobile'  => true,
        'desktop' => true,
    ],
    'phaser-cat' => [
        'name'    => 'Phaser Cat',
        'tag'     => 'fighting feline',
        'license' => 'MIT',
        'git'     => 'https://github.com/DaxChen/phaser-cat.git',
        'require' => ['yarn'],
        'build'   => ['yarn install', 'yarn run deploy'],
        'mobile'  => false,
        'desktop' => true,
    ],
    '8queens' => [
        'name'    => '8 Queens',
        'tag'     => 'chess puzzle',
        'license' => 'MIT',
        'git'     => 'https://github.com/attogram/8queens.git',
        'require' => ['composer'],
        'build'   => ['composer install'],
        'mobile'  => false,
        'desktop' => true,
    ],
    'pacman' => [
        'name'    => 'pacman',
        'tag'     => 'eat the dots',
        'license' => 'MIT',
        'git'     => 'https://github.com/mumuy/pacman.git',
        'mobile'  => false,
        'desktop' => true,
    ],
    'polybranch' => [
        'name'    => 'PolyBranch',
        'tag'     => 'fly thru trees',
        'license' => 'UNKNOWN', 
        'git'     => 'https://github.com/gbatha/PolyBranch.git',
        'index'   => 'polybranchweb/',
        'mobile'  => false,
        'desktop' => true,
    ],
];
